### ISSUE TITLE
better app start window

### ISSUE THREAD

**Issue by alexkaessner** [tid-kijyun/XcodeSourceEditorExtension-Alignment#10]
![screenshot](https://cloud.githubusercontent.com/assets/6615076/22432301/c20f403c-e714-11e6-9317-93ea2ca088e4.png)

I know the app is only the wrapper for the Xcode extension, but you could use the main window of the app itself to tell the people how to activate the extension. Currently it's just a wasted blank window without any link to the repository…

I guess most of the devs know this, but I also think not everyone knows this.

**Comment by tid-kijyun** [comment]
I improved it with version 1.1.0. This version is waitting for review in app store.

![screen shot 2017-02-09 at 17 09 15](https://cloud.githubusercontent.com/assets/1665104/22777668/521450de-eef7-11e6-98a3-82fe4e1b9188.png)
