### ISSUE TITLE
Not working in the latest version of Xcode

### ISSUE THREAD

**Issue by c137Choi** [tid-kijyun/XcodeSourceEditorExtension-Alignment#19]
macOS Big Sur
Xcode 12.2
Alignment-Align not showing in source code Editor

**Comment by tid-kijyun** [comment]
@OriTheElf Thank you for your report.  
I've pushed a new version to App Store that fixed this issues. Please wait for the review to complete.

**Comment by c137Choi** [comment]
> @OriTheElf Thank you for your report.
> I've pushed a new version to App Store that fixed this issues. Please wait for the review to complete.

Cool, thank your.
