### ISSUE TITLE
Build failed in 8 beta 6

### ISSUE THREAD

**Issue by willlarche** [tid-kijyun/XcodeSourceEditorExtension-Alignment#2]
Downloaded the project as a .zip. Made no changes.

![screen shot 2016-08-30 at 12 02 29](https://cloud.githubusercontent.com/assets/1271525/18096847/a5d3f7a2-6ea9-11e6-97d4-44360b229df0.png)

**Comment by MellongLau** [comment]
need to replace `func public perform...` with`public func perform(with invocation: XCSourceEditorCommandInvocation, completionHandler: @escaping (Error?) -> Swift.Void) {`
