### ISSUE TITLE
How do I get this extension to be installed permanently for Xcode? If I quit this app, the extension disappears.

### ISSUE THREAD

**Issue by toddfreese** [tid-kijyun/XcodeSourceEditorExtension-Alignment#5]

**Comment by tid-kijyun** [comment]
1. Open `XcodeSourceEditorExtension-Alignment.xcodeproj`
2. Enable target signing for both the Application and the Source Code Extension using your own developer ID
3. Product > Archive
4. Right click archive > Show in Finder
5. Right click archive > Show Package Contents
6. Open Products, Applications
7. Drag XcodeSourceEditorExtension-Alignment.app to your Applications folder
8. Run XcodeSourceEditorExtension-Alignment.app and exit again.
9. Go to System Preferences -> Extensions -> Xcode Source Editor and enable the extension (This may not be necessary.) 
10. The menu-item should now be available from Xcode's Editor menu.

**Comment by tid-kijyun** [comment]
I've released Alignment on the Mac App Store.
You can install this extension.

[![download_on_the_mac_app_store_badge_us-uk_165x40](https://cloud.githubusercontent.com/assets/1665104/19629909/de5c7a64-99b9-11e6-88fc-2a39c8849920.png)](https://itunes.apple.com/us/app/alignment-for-xcode/id1168397789?ls=1&mt=12)

**Comment by toddfreese** [comment]
I don't get a Source Editor Extensions options in Sys Prefs->Extensions . This is running El Cap. Do I need anything special to make it appear?
