### ISSUE TITLE
borks on +=

### ISSUE THREAD

**Issue by genedelisa** [tid-kijyun/XcodeSourceEditorExtension-Alignment#6]
This will align on = just fine.

But if you have +=, it will still align on = instead of +=

example:

```
s += "foo"
s += "bar"
```

becomes

```
s +  = "foo"
s +  = "bar"
```

**Comment by tid-kijyun** [comment]
I've fixed this issue.

**Comment by genedelisa** [comment]
Nice. Keep up the good work!
