### ISSUE TITLE
Incorrect alignment Chinese characters

### ISSUE THREAD

**Issue by hex2010** [tid-kijyun/XcodeSourceEditorExtension-Alignment#7]
In most cases Chinese characters are double width:

```swift
        //  Chinese, not works
        c["黑"]      = _bgr(0x000000)
        c["昏灰"]     = _bgr(0x696969)
        c["灰"]      = _bgr(0x808080)
        c["暗灰"]     = _bgr(0xA9A9A9)
```

![chnsaw](https://cloud.githubusercontent.com/assets/13978929/19971101/f87e4d04-a1d5-11e6-8663-d0019277a91f.png)

**Comment by tid-kijyun** [comment]
It is not possible to align the code that contains multi-byte characters.

BTW, Is it possible to align the code manually? Please tell me if there is a way.

**Comment by hex2010** [comment]
my bad. 
In a "correct" configured editor environment, Chinese characters should display as exact double width squares,  so we can simply double the size for those chars.  

![cjk](https://cloud.githubusercontent.com/assets/13978929/19976473/c2dc8a64-a1e7-11e6-8407-65e512fa264c.png)

**Comment by tid-kijyun** [comment]
I agree with you, so I can not deal with this issue.

Thanks
