### ISSUE TITLE
Ability to use align based on Colon ':'

### ISSUE THREAD

**Issue by mohamede1945** [tid-kijyun/XcodeSourceEditorExtension-Alignment#8]
First of all thank you so much for the great extension!

I'd like to ask for a new feature. The ability to handle not only assignment but also ":" this is going to be useful for functions. For example:
``` swift
init(imageService: ImageService,
       dataRetriever: DataRetriever<[String]>,
       audioViewPresenter: AudioBannerViewPresenter,
       bookmarksPersistence: BookmarksPersistence,
       lastPagePersistence: LastPagesPersistence)
```
would become:
``` swift
init(imageService           : ImageService,
     dataRetriever          : DataRetriever<[String]>,
     audioViewPresenter     : AudioBannerViewPresenter,
     bookmarksPersistence   : BookmarksPersistence,
     lastPagePersistence    : LastPagesPersistence)
```

**Comment by BrikerMan** [comment]
Thank for your work and @mohamede1945 advice. Really need this.

**Comment by BrikerMan** [comment]
added Ability to use align based on Colon ':' #11

**Comment by tid-kijyun** [comment]
@BrikerMan Thank you for your PR. 👍 
I'll improve so that users can choose to enable / disable this feature, then I'll release a new version.

**Comment by tid-kijyun** [comment]
I applied for a new version(1.1.0) to iTunes Connect. Please wait for a review.

**Comment by tid-kijyun** [comment]
Version 1.1.0 has been released on the App Store.

**Comment by plm75** [comment]
[Feature request]: 
Thanks for this awesome plugin.  For type declaration, would it be possible to choose not to have any space before the colon ?

example : 
```
var somePropertyA: String!
var somePropertyB: String!

// instead of 
var somePropertyA : String!
var somePropertyB : String!
```

Thanks
